
### Expander Graphs
  The expander graph based on literary definition, are the graph have high connectivity or in other words, from every subset, the graph keeps on expanding.In many application like connected computing elements or communication networks,such highly connected components are required but it is always desirable that such connectedness is achieved with sparse constructions. So for example, the complete graph has great expansion, but lacks the sparsity. So when strictly defined, the expanders are the family of the graphs which keeps on expanding with high connectivity but with sparse number of edges. 
-- TODO: recap of expanders
There are different definitions which uses different parameters for quantifying expansion

A. Vertex Expansion- It uses the baselines concept that every vertex is has high number of neighbors and quantifiable parameter is defined on the vertex set, having least value.

B. Edge Expansion - It measures the connectivity in terms of edges such that number of edges crossing the vertex sets are high when compared with edges internal to both edges. Like Vertex expansion, the quantification is done based on the set having minimum value of measure.

C. Spectral Expansion- It defined on concept of random walks, which will converge faster if the graph is highly connected. Specifically it is defined in terms of adjacency matrix, where the \Lambda- expander is defined as the one where are the all eigen values except for the largest are bounded 
$$
-\lambda \leq \underset{i\neq 1}{\lambda_i} \leq \lambda
$$ 

### Expander Mixing Lemma
  The expander mixing lemma suggest that the edges are evenly distributed across edges. In particular, it is associated with quasirandomness which states that edges going between every two sets S,T are closure to the average expected value.
$$
  |E(S,T)-\frac{d|S||T|}{n}|\leq \lambda \sqrt{|d||n|}
$$ 

### Ramanujan Bounds
  As seen in the expander mixing lemma, the lower the value of $\lambda$, the cross edge weight more close to the average, which means edges are uniformly distributed. A bound known as alan-bopanna, states lower limit for second-eigenvalue  of d-regular graph G_n. The bound is as given below
$$
    \lambda \leq 2\sqrt{d-1} − o(1)\:\text{ As n->} \infty
$$

### The Twice Ramanujan Sparsifier

-- TODO: illustration of what happens in the algorithm iteratively on a complete graph.